### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by luisstd** [Frachtwerk/essencium-frontend#221]
**DESCRIPTION**
Currently, several tests are missing, including unit tests and end-to-end tests. All these tests should be added for good code coverage.

**SCOPE**
List of components with missing tests:

**Unit Tests**
- [x] `Contact.tsx`
- [ ] `Login.tsx`
   - check local storage
- [ ] `Profile.tsx`
- [x] `SetPassword.tsx`
- [ ] `AddRole.tsx`
- [ ] `TablePagination.tsx`
- [ ] `Table.tsx`

Each of these components contains sub-components that could be individually tested as well.

**End-to-end Tests**
- [ ] Testing functionality for selecting color scheme
	- Go to Homepage
	- Change ColorSchema & and check if new ColorSchema is applied 
	- change ColorSchema back 
- [ ] Testing functionality for selecting a language
- [ ] Testing functionality for open search bar (click or cmd + k) and navigate to different page 
- [ ] Testing functionality for changing password  
	- Go to Profile 
	- Change tab to "Change Password"
	- Update password 
	- check if user is logged out 
	- login with new credetials 
	- go to profile and change password back to original
- [ ] Addition to `LoginView.tsx` test: testing, if user and token are stored in the local storage  
- Testing functionality for Views:
  - [ ] Testing functionality for using contact form
  - [x] `ProfileView.tsx`
  - [ ] `RightsView.tsx`
  - [x] `HomeView.tsx` 
  - [x] `UserView.tsx`: Testing functionality for adding / editing and deleting a user
  - [ ] Updating and resetting translations
  - [ ] `RolesView.tsx`: Testing functionality for adding / editing and deleting a role
	- go to RolesView 
	- add a new role and save
	- check if role exists 
	- click on edit button and change role data 
	- check if new data is displayed 
	- click on delete button and confirm delete dialog 
	- check if role is deleted
  - [ ] Testing functionality for assigning a role
	- go to RolesView 
	- add a new role and save
	- go to UsersView 
	- assign new role to user 
	- check if new role is assigned 
	- go to RolesView 
	- click on delete button 
	- check if error message is displayed 
	- go to UsersView 
	- assign original role to user 
	- go to RolesView 
	- delete role 
	- check if role is deleted
  - [ ]  Check UI if certain rights are toggled

**Comment by qhantom** [comment]
Makes sense to implement CodeCov first: https://github.com/Frachtwerk/essencium-frontend/issues/207
