### ISSUE TITLE
Fix layout flickering on initial load

### ISSUE THREAD

**Issue by qhantom** [Frachtwerk/essencium-frontend#365]
**Describe the bug**
When loading Essencium, there is a short flickering of non-styled HTML.

**To Reproduce**
1. Go to [ https://staging.essencium.dev](https://staging.essencium.dev)
2. See flickering

**Expected behavior**
HTML is shown with its CSS.

**Screenshots**
![image](https://github.com/Frachtwerk/essencium-frontend/assets/54100938/f8716aa1-335f-4c8e-96db-b3aa4b878d38)

**Comment by PhilKsr** [comment]
Could be an issue with pnpm. After some researches and trials I found out that the FOUC doesn't exist with yarn like in the [mantine-nextjs-template](https://github.com/mantinedev/next-pages-template). I adapted most of the code but FOUC is still there.
The other case would be incorrect ssr logic. But I compared the template with essencium and most of the logic is the same.

**Comment by qhantom** [comment]
> Could be an issue with pnpm. After some researches and trials I found out that the FOUC doesn't exist with yarn like in the [mantine-nextjs-template](https://github.com/mantinedev/next-pages-template). I adapted most of the code but FOUC is still there. The other case would be incorrect ssr logic. But I compared the template with essencium and most of the logic is the same.

Thanks for investigating! I'll have a look at it soon.
