### ISSUE TITLE
Page stops responding when using userTable pagination 

### ISSUE THREAD

**Issue by CathrinTruchan** [Frachtwerk/essencium-frontend#410]
**Describe the bug**
The page stops responding when using the `tablePagination` in `userTable`.

**To Reproduce**

1. go to /users
2. click on selectComponent to change size of displayed items in the table 
3. try to use the page 

**Expected behaviour**
The table should re-render and the number of items in table should change.

**Comment by qhantom** [comment]
Would you mind putting a meaningful title to the top? 🙂 @CathrinTruchan

**Comment by CathrinTruchan** [comment]
> Would you mind putting a meaningful title to the top? 🙂 @CathrinTruchan

Sorry, forgot 😬
