### ISSUE TITLE
Vercel deployments fail arbitrarily

### ISSUE THREAD

**Issue by qhantom** [Frachtwerk/essencium-frontend#458]
**Describe the bug**
Sometimes, the Vercel `app` deployment fails with the following error:

`Error: The file "/vercel/path0/packages/app/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.`

It looks like a misconfig in the Vercel config file.

**Comment by qhantom** [comment]
@PhilKsr @CathrinTruchan 

I changed the Vercel build configuration inside the Vercel dashboard itself. You can specific, how Vercel builds your app via which command. I had set it to the `nx` build command which was the issue. Vercel couldn't handle it properly so I changed it to the following:

![image](https://github.com/Frachtwerk/essencium-frontend/assets/54100938/e98e15a8-cd7d-4e10-ab19-c2fc9c2a25fe)

It tested it and it worked properly 🚀

**Comment by PhilKsr** [comment]
> @PhilKsr @CathrinTruchan
> 
> I changed the Vercel build configuration inside the Vercel dashboard itself. You can specific, how Vercel builds your app via which command. I had set it to the `nx` build command which was the issue. Vercel couldn't handle it properly so I changed it to the following:
> 
> ![image](https://private-user-images.githubusercontent.com/54100938/295343484-e98e15a8-cd7d-4e10-ab19-c2fc9c2a25fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODcyMTAsIm5iZiI6MTcwNDg4NjkxMCwicGF0aCI6Ii81NDEwMDkzOC8yOTUzNDM0ODQtZTk4ZTE1YTgtY2Q3ZC00ZTEwLWFiMTktYzJmYzljMmEyNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDExNDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZmE2NzM5M2EzNjM4ZTU0MmJhMzk4YTViNGM0NmNjY2JmZDEwM2Y1NTM5MmU2MDg1MDQ0ZjBjMzlhNjZkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mOsaHfSgxl_6TVfrxAR3UDqPZXUFC_6n0l4wXCg15RQ)
> 
> It tested it and it worked properly 🚀

Very nice! and makes sense. Thanks for investigating and fixing! 🤌

**Comment by CathrinTruchan** [comment]
> @PhilKsr @CathrinTruchan
> 
> I changed the Vercel build configuration inside the Vercel dashboard itself. You can specific, how Vercel builds your app via which command. I had set it to the `nx` build command which was the issue. Vercel couldn't handle it properly so I changed it to the following:
> 
> ![image](https://private-user-images.githubusercontent.com/54100938/295343484-e98e15a8-cd7d-4e10-ab19-c2fc9c2a25fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODk2NjgsIm5iZiI6MTcwNTM4OTM2OCwicGF0aCI6Ii81NDEwMDkzOC8yOTUzNDM0ODQtZTk4ZTE1YTgtY2Q3ZC00ZTEwLWFiMTktYzJmYzljMmEyNWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA3MTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZGJhMWM0ZDliZmRhNzI5ZTFjZjMxZmZjZjg5YzY1MTM0YzkyOGY3MTAzNmYwZjhkZTQ4MmU5YTViNzI3YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PNQzWU9UcBr8tsa1ucp9rSWHt3MPlv-vHUc_C8uHJUc)
> 
> It tested it and it worked properly 🚀

Nice!! Thanks 🚀
