### ISSUE TITLE
Fix code scanning alert - axios: exposure of confidential data stored in cookies

### ISSUE THREAD

**Issue by PhilKsr** [Frachtwerk/essencium-frontend#469]
Tracking issue for:
- [ ] https://github.com/Frachtwerk/essencium-frontend/security/code-scanning/10

**Comment by PhilKsr** [comment]
@qhantom to update axios in this case as peer dependencie we need to migrate nx and nx cloud to the newest versions.

What do you think? Maybe we can talk about what I should be aware of when migrating nx and nx cloud to v17.

**Comment by qhantom** [comment]
> @qhantom to update axios in this case as peer dependencie we need to migrate nx and nx cloud to the newest versions.
> 
> 
> 
> What do you think? Maybe we can talk about what I should be aware of when migrating nx and nx cloud to v17. 

Yes sure lets have a chat about it 💬
