### ISSUE TITLE
Improve media query |  Sidebar overlaps the dark/light mode button 

### ISSUE THREAD

**Issue by ketnek** [Frachtwerk/essencium-frontend#514]
**Describe the bug**
Under the breakpoint of 991px the sidebar overlaps the dark/light mode button.

**To Reproduce**

1. Go to any page were you can see the sidebar and the dark/light mode button
<img width="1028" alt="Bildschirmfoto 2024-02-18 um 11 42 29" src="https://github.com/Frachtwerk/essencium-frontend/assets/113082466/a5c914da-5634-464b-be4c-9b0b85c675c0">

2. Shrink the window width of the browser under 991px
<img width="967" alt="Bildschirmfoto 2024-02-18 um 11 42 51" src="https://github.com/Frachtwerk/essencium-frontend/assets/113082466/2e6f66f1-676d-41e1-82b4-4669ee81c5c5">

3. Try to change between light and dark mode using the button
4. See that the sidebar starts to overlap the button and makes it inpossible to change between dark and light mode
<img width="967" alt="Bildschirmfoto 2024-02-18 um 11 43 05" src="https://github.com/Frachtwerk/essencium-frontend/assets/113082466/ed8af2bb-076b-4ab3-a725-fb233713e42b">

**Expected behaviour**
Under the breakpoint of 991px the button for light and dark mode stays at the right of the screen to prevent overlapping.

**Comment by qhantom** [comment]
Thanks for creating! 🙂

**Comment by ketnek** [comment]
You are welcome!😁
