### ISSUE TITLE
error on feedback submit

### ISSUE THREAD

**Issue by PhilKsr** [Frachtwerk/essencium-frontend#678]
**Describe the bug**
The feedback widget gets an 504 error on submit. 

**To Reproduce**

1. Go to essencium app
2. Click on feedback widget
3. Fill and submit

**Expected behaviour**
Feedback should be sent correctly

**Screenshots**
![Bildschirmfoto vom 2024-11-22 07-00-07](https://github.com/user-attachments/assets/62449485-bc1c-448a-9d6c-5af4283e929d)

- [ ] fix api call or endpoint

**Comment by qhantom** [comment]
Vercel function invokation time limit is 5 seconds, this endpoint needs more time. For us, this is not solveable unless we upgrade to pro plan or host the staging environment on a different platform.
